{
 "title": "Camunda",
 "description": "Camunda metrics dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Executable Jobs",
   "type": "gauge",
   "description": "Jobs ready to be executed (past due date)",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "camunda_executable_jobs" }
   ]
  },
  {
   "title": "Message Jobs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "camunda_message_jobs" }
   ]
  },
  {
   "title": "Active Message Event Subscriptions",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "camunda_active_message_event_subscriptions"
    }
   ]
  },
  {
   "title": "Active Incidents",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "targets": [
    { "expr": "camunda_active_incidents" }
   ]
  },
  {
   "title": "Active Signal Event Subscriptions",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "camunda_active_signal_event_subscriptions"
    }
   ]
  },
  {
   "title": "Active Compensate Event Subscriptions",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "camunda_active_compensate_event_subscriptions"
    }
   ]
  },
  {
   "title": "Active Conditional Event Subscriptions",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "camunda_active_conditional_event_subscriptions"
    }
   ]
  },
  {
   "title": "Executable Timer Jobs",
   "type": "gauge",
   "description": "Timers that are ready to be executed (past due date)",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "camunda_executable_timer_jobs" }
   ]
  },
  {
   "title": "Active Locked External Tasks",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "camunda_active_locked_external_tasks"
    }
   ]
  },
  {
   "title": "Active Not Locked External Tasks",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "camunda_active_not_locked_external_tasks"
    }
   ]
  },
  {
   "title": "Active External Tasks",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "camunda_active_external_tasks" }
   ]
  },
  {
   "title": "Timer Jobs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "camunda_timer_jobs" }
   ]
  },
  {
   "title": "Process Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Process Instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "camunda_active_process_instances"
    }
   ]
  },
  {
   "title": "Completed Process Instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "camunda_completed_process_instances"
    }
   ]
  },
  {
   "title": "Process Definitions and Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Process Definitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "camunda_active_process_definitions"
    }
   ]
  },
  {
   "title": "Active Deployments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    { "expr": "camunda_deployments" }
   ]
  }
 ]
}