server:
  port: 8080

spring:
  profiles.active: local
  application.name: camunda-base
  main.banner-mode: off
  jpa:
    hibernate.ddl-auto: update
    open-in-view: false

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    filter:
      create: All tasks