global:
  scrape_interval: 5s
  external_labels:
    monitor: "services-monitor"

scrape_configs:
  - job_name: "Camunda Service"
    metrics_path: "/manage/prometheus"
    static_configs:
      - targets:
          - host.docker.internal:8080

  - job_name: "Node Exporter"
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: "Postgres Exporter"
    static_configs:
      - targets:
          - postgres-exporter:9187

  - job_name: "Prometheus"
    static_configs:
      - targets:
          - localhost:9090