---
name: Build project
on:
  push:
    branches:
      - master
    paths:
      - ".github/**"
      - "src/**"
      - "Dockerfile"
      - "build.gradle"
      - "gradle.properties"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"
          cache: "gradle"

      - name: Validate
        uses: pre-commit/action@v3.0.0

      - name: Build project
        run: ./gradlew clean build
