---
name: Publish
on:
  push:
    tags:
      - "v*.*"
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: romanowalex/camunda-base:${{ github.ref_name }}
          push: true

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          repository: romanowalex/camunda-base
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true

      - name: Create release
        uses: softprops/action-gh-release@v2
